### ISSUE TITLE
スマホで見るとたまにメッセージが飛び出す

### ISSUE THREAD

**Issue by wattai** [wattai/simple-othello#26]
## 解決策

css で

```css
.opponent-message {
  ...
  overflow: scroll;
  ...
}
```

を追記する
